name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        LOINC_USER_NAME: ${{secrets.LOINC_USER_NAME}}
        LOINC_PASSWORD: ${{secrets.LOINC_PASSWORD}}
        ENV: PIPELINE
    - name: Restore dependencies
      run: dotnet restore src; dotnet restore test
    - name: Build
      run: dotnet build src --no-restore; dotnet build test --no-restore
    - name: Test
      run: dotnet test test --no-build --verbosity normal
